### ISSUE TITLE
Statements/Tests

### ISSUE THREAD

**Issue by mpriorust** [CastleLab/COMP5111-assignment-Student-Version#13]
Is it possible that one test executes one statement multiple times? If so, shall the result (pass/fail) of the test be counted once or multiple times?

**Comment by aaromine** [comment]
Yes, one statement can be executed many times by a same test case. 
If you refer to the definition of the algorithm, e.g., `Ochiai`, it is clear that the numbers used in the formula is `the number of test cases`, instead of number of executions. Therefore, the result of each test case should be counted `only once`.
